# Generated by Django 3.1.7 on 2021-04-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
    ]
