# Generated by Django 3.1.7 on 2021-04-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_prod_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prod_Gallery',
            new_name='ProdGallery',
        ),
    ]
