# Generated by Django 3.1.7 on 2021-04-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210412_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodgallery',
            old_name='image',
            new_name='images',
        ),
    ]
